### ISSUE TITLE
Refactor ArrayMath

### ISSUE THREAD

**Issue by FG-TUM** [AutoPas/AutoPas#264]
**Is your feature request related to a problem? Please describe.**
ArrayMath is not a proper class and is sometimes fed with values that could be precomputed.

**Describe the solution you'd like**
- Change ArrayMath to a namespace with free functions.
- `constexpr` functions.

**Describe alternatives you've considered**
Hope the compiler optimizes everything by itself ¯\\\_(^\_^)\_/¯

**Additional context**
We already did the namespace thing to e.g. `inBox`.

**Comment by Garfield96** [comment]
I'll do the requested changes. However, we should think about changing it completely in the future, since it currently lacks functionality:
* type conversions are not provided, especially signed to unsigned and vise versa would be helpful
* chaining of `ArrayMath` operations is extremely inefficient, since each invocation of a method in `ArrayMath` results in a new loop

There are two possible solutions:
1. rewrite the whole class
2. use an external lib

**Comment by FG-TUM** [comment]
are there actually any cases where we need to chain stuff (yet)?

**Comment by Garfield96** [comment]
Here are some examples:
https://github.com/AutoPas/AutoPas/blob/c7697868034b9e467391f0a159e443cbee73bb18/src/autopas/containers/linkedCells/LinkedCells.h#L205-L206

https://github.com/AutoPas/AutoPas/blob/c7697868034b9e467391f0a159e443cbee73bb18/src/autopas/containers/linkedCells/traversals/C18Traversal.h#L127-L129

https://github.com/AutoPas/AutoPas/blob/c7697868034b9e467391f0a159e443cbee73bb18/src/autopas/containers/cellPairTraversals/CBasedTraversal.h#L43-L45

**Comment by Garfield96** [comment]
@Njan0 introduced the Eigen lib in PR #265. Maybe this would be an alternative.

**Comment by SteffenSeckler** [comment]
well the compiler is allowed to merge multiple loops so i don't see a huge benefit of changing this.
