### ISSUE TITLE
Broken Link to continuous-integration/jenkins/branch

### ISSUE THREAD

**Issue by FG-TUM** [AutoPas/AutoPas#28]
In pull requests the link to `continuous-integration/jenkins/branch` seems to be broken due to a duplicate forward slash (`//`).

**Comment by NeoTheThird** [comment]
Sorry about that, it's [a jenkins bug](https://issues.jenkins-ci.org/projects/JENKINS/issues/JENKINS-50961). I'll look into it tomorrow.

**Comment by NeoTheThird** [comment]
So, as of #29, simply overriding this is not trivial. Someone from the jenkins team is looking into [the issue](https://issues.jenkins-ci.org/projects/JENKINS/issues/JENKINS-50961?filter=allopenissues) right now. Since this issue is not highly critical, i'd propose giving them maybe two weeks to sort it out, if it's not fixed by then, i'll look into getting a patch for it accepted myself. Does that work for you?

**Comment by SteffenSeckler** [comment]
jep that sound reasonable


Am 2. Mai 2018 6:48:20 nachm. schrieb Jan Sprinz <notifications@github.com>:

**Comment by SteffenSeckler** [comment]
this only affects the link over www5.informatik* doesn't it?
the vmbungartz10 one looks ok

**Comment by SteffenSeckler** [comment]
seems also more like a configuration error than anything else:
http://vmbungartz10.informatik.tu-muenchen.de/mardyn/job/AutoPas-Multibranch/
https://www5.in.tum.de/jenkins/mardyn/job/AutoPas-Multibranch/
always redirected to:
http://vmbungartz10.informatik.tu-muenchen.de/mardyn//job/AutoPas-Multibranch/
(double slash)
I have fixed the php file, so the double slash is no problem anymore.

however, the webhook still doesn't work. don't ask me why.

**Comment by SteffenSeckler** [comment]
I have changed the default jenkins url to the vmbungartz10. this should circumvent most problems.

**Comment by NeoTheThird** [comment]
Interesting! Still, Jenkins should try to sanitize the URL and check if it's actually reachable... I'll update the report. Thanks.
