### ISSUE TITLE
data race in C01 traversal combine soa

### ISSUE THREAD

**Issue by SteffenSeckler** [AutoPas/AutoPas#285]
**Describe the bug**
There appears to be a data race in the c01 traversal, see here:
http://vmbungartz10.informatik.tu-muenchen.de/mardyn/blue/rest/organizations/jenkins/pipelines/AutoPas-Multibranch/branches/PR-278/runs/17/nodes/96/steps/200/log/?start=0

**To Reproduce**
* use autopas/autopas-build-archer docker image
* cmake: `CXXFLAGS=-Wno-pass-failed CC=clang-archer CXX=clang-archer++ cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DAUTOPAS_USE_VECTORIZATION=OFF ..`
* build: `ninja -j 4`
* export TSAN_OPTIONS="ignore_noninstrumented_modules=1" && ctest --verbose

**Expected behavior**
There is no data race

**Comment by SteffenSeckler** [comment]
the problem lies in the following:

1. thread 1 copies the soa buffer of thread 2, line 219 of C01Traversal.h:
   ```C++
   combinationSlice[currentSlice]._particleSoABuffer.append(otherCell._particleSoABuffer);
   ```
2.  thread 2 uses the own soa to calculate things, lines 230, 233,235
   ```C++
   this->_cellFunctor.processCellPair(baseCell, combinationSlice[slice]);
   this->_cellFunctor.processCell(baseCell);
   this->_cellFunctor.processCellPair(baseCell, combinationSlice[slice]);
   ```

possible workaround:
this is not synced and can lead to read after write data races. You will need to use another slice for the  own cell.

**Comment by Garfield96** [comment]
I don't think that this is a data race/bug. Its true that both operations are not synced and the execution order is therefore arbitrary making the force values inside of the buffer not deterministic. But the force values inside the buffer are never used to calculate something (no N3). I'm aware of the fact that copying these unused values (done in line 219) is not optimal, since it causes unnecessary load and lets archer think were is a data race. However, to resolve this problem it would be necessary to know which values are computed by a functor and which values are necessary to do that. This information is currently not available.

**Comment by FG-TUM** [comment]
Ok, for now, we will tell the sanitizer to ignore this, however, this is not a viable long term solution.
@Garfield96 since you already came up with an idea for more selective loading of the SoAs it would be cool if you could implement this in order to resolve this properly. ;)
