### ISSUE TITLE
C04SoA Traversal is not compared with others in tests

### ISSUE THREAD

**Issue by HobbyProgrammer** [AutoPas/AutoPas#309]
I tried to replace the old view stuff of `SoA` in `C04SoATraversal` with my new `SoAView` in #299 , and it worked instantly, at least the tests didn't fail. That is impossible, so I checked the tests.

**Describe the bug**
The tests don't check if the `C04SoATraversal` gives correct results.

**To Reproduce**
1. Go to `C04SoACellHandler.h`
2. Remove line 251: `this->_cellFunctor.processCellPair(*cell1, currentCS);` (it is pretty important, I think)
3. See that all tests pass.

**Expected behavior**
Some test should fail if I destroy the `C04SoATraversal` implementation.

**Comment by HobbyProgrammer** [comment]
@Garfield96 I just tested the the `C04SoATraversal` against other traversals on master, and it seems like it yields different forces. How did you check that it is correct?

**Comment by Garfield96** [comment]
There are some tests which applies to C04 SoA traversal:
- The interface test covers the case that two particles are in the same cell. 
- Than there also is a test which covers the interaction between two cells in the base slice. 

Line 251 describes interactions between two cells which are not in the base slice. There is no dedicated test case for that, since at the time of writing `C04SoATraversal` it looks like this a redundant thing to do, because Steffen told me he wants to extend the interface test soon. Nevertheless, I checked it by having a look at the force values using a debugger.

**Comment by HobbyProgrammer** [comment]
I just pushed the test I used to #301. You can have a look at it, but it seems like the `C04SoATraversal` results in other forces than the others.

**Comment by SteffenSeckler** [comment]
see also #354
