### ISSUE TITLE
VerletClustersColoringTraversal should probably not inherit from CBasedTraversal 

### ISSUE THREAD

**Issue by SteffenSeckler** [AutoPas/AutoPas#329]
**Describe the bug**
VerletClustersColoringTraversal currently inherits from CBasedTraversal, but doesn't use any of its functionality and only passes random initial values to it.

**Comment by HobbyProgrammer** [comment]
Actually, it uses its most important function:
https://github.com/AutoPas/AutoPas/blob/ecd566ca51b27eb558d9e5eb0f3c8fc6d1a0238d/src/autopas/containers/verletClusterLists/traversals/VerletClustersColoringTraversal.h#L105

I wasn't sure if I wanted to reuse the CBasedTraversal for this, since it really was written for the LinkedCells container, but this method came in handy, so I did it.

**Comment by SteffenSeckler** [comment]
ok will close it as invalid.
Fyi, as far as I know, that `std::forward` you are using there should rather be a `std::move`, as `std::forward` normally is only needed for forwarding references (https://en.cppreference.com/w/cpp/language/reference#Forwarding_references), i.e., a function with the template of the form:
```C++
template<class T>
int f(T&& x) {                    // x is a forwarding reference
    return g(std::forward<T>(x)); // and so can be forwarded
}
```
