### ISSUE TITLE
long range interactions

### ISSUE THREAD

**Issue by SteffenSeckler** [AutoPas/AutoPas#4]
Still far off:
how can we handle long-range interaction?
simply using the iterators?

**Comment by FG-TUM** [comment]
FMM Example using only iterators:
#370 

Start of an FMM implementation:
#371

**Comment by FG-TUM** [comment]
It was concluded that full FMM integration is not easily feasible since it requires a domain decomposition that is not necessarily the same as the cell structure provided by autopas containers.
Therefore the aforementioned branches were not merged but may serve as an example of how to still implement an FMM with autopas.
These examples might break with future versions of AutoPas.
