### ISSUE TITLE
Reduced SoAType for Verlet Lists

### ISSUE THREAD

**Issue by SteffenSeckler** [AutoPas/AutoPas#61]
**Is your feature request related to a problem? Please describe.**
I would like to add a custom SoAType to the VerletList. Thus making it possible to only store the necessary information as SoA's, i.e. position (and id).

**Describe the solution you'd like**
To implement this, the Cells need a different SoA structure. This, however, also changes the definition of iteratePairwise(Functor<Particle, ParticleCell>), as particleCell is a template argument. A variety of solutions exist:
1. remove SoA from Cell and put it somewhere else
2. make VerletList no longer inherit from LinkedCells, but rather do delegation.
3. make the functor accept arbitrary ParticleCells, by making it a function template instead of a class template. This, however, will require the removal of the functor base class.

the second option is probably the cleanest.
@FG-TUM what do you think?

**Additional context**
see branch https://github.com/AutoPas/AutoPas/tree/feature/smallVerletCellSoA

**Comment by FG-TUM** [comment]
ad 1. One could think about creating AoS and SoA Cells
ad 2. This is generally a good Idea. If they share functionality there should be a common base class but this inheritance now is a bit confusing
ad 3. Well since our "Functors" are no actual functors but more like Objects with functions and state, I would not be opposed to restructuring this. However this would probably mean deep changes in AutoPas
