### ISSUE TITLE
ParticleContainerInterface::numParticles() probably inconsistent

### ISSUE THREAD

**Issue by FG-TUM** [AutoPas/AutoPas#718]
**Describe the bug**
Currently `numParticles()` seems to report the `size` of particle vectors in cells. This means it would count particles that are marked for deletion (aka dummies). However, ClusterTowers do subtract the number of dummies they insert to fill up the last cluster and other containers might do weird things too.

**Expected behavior**
I see three options:
1. Consistently count **everything**.
2. Count every particle that is not a dummy. (This would probably be in O(N) instead of O(1) as every other solution because we don't track deletion on cell level).
3. Count everything that was part of the simulation. So count particles that are marked as deleted but not those that were inserted for data structure reasons. For the cluster towers this is easy. Not sure about other / future containers.

We should review where the function is used to get a clearer picture what we need. Total particle count is tracked in the `LogicHandler` so the high-level interface is not impacted by this.

No matter which one we choose we should clearly specify what the function does in the documentation.

**Additional context**
While we are at it, rename the function to `getNumberOfParticles()`

**Comment by FG-TUM** [comment]
Can be resolved by resolving #765 via counting how many particles of which type are in each cell

**Comment by dmartin13** [comment]
I have looked into the usage of `numParticles()`:
So the function is mostly used in a way that requires the number of all particles including dummies (e.g. out of bounds checks or reallocation and copying of buffers, and so on). There are a few exceptions (e.g. in `CellFunctor`) where I think the number of owned and halo particles would be enough.
I would have the following idea: we could rename the `numParticles()` function to `size()`, since that is more in line with its intended use. For example, there is also a function `empty()` for each cell that returns `numParticles()` (so just `_particles.size()`). In some way, this renaming would be more in line with `std::size`.
In addition, we can then introduce a function `getNumberOfParticles()` that returns the sum of the two counters for owned and halo particles for each cell.

**Comment by FG-TUM** [comment]
I like the idea. `getNumberOfParticles()` could also take an `IteratorBehavior` as an optional argument like the one in the main interface. 
@dmartin13 feel free to implement it 😇
