### ISSUE TITLE
Add initial force calculation to md-flexible

### ISSUE THREAD

**Issue by thesamriel** [AutoPas/AutoPas#816]
**Describe the bug**
There should be an initial force calculation before starting into the main simulation time loop. Currently, the old forces used for the first position and velocity updates are still 0.

**Comment by thesamriel** [comment]
Potentially, we can simply change the order of calculations in our time loop. 
From our current order **x** -> **F** -> **v**
to: **F** -> **v** -> **x**

**Comment by SamNewcome** [comment]
> Potentially, we can simply change the order of calculations in our time loop. From our current order **x** -> **F** -> **v** to: **F** -> **v** -> **x**

In this case the velocity calculation is still done without an old **F** plus you risk over complicating things (e.g. the actual time integration loop starts before the **x** which is in the middle of the iteration).

But I fully agree with the first point.

**Comment by FG-TUM** [comment]
In principle, I agree that ignoring `oldF` in the first step introduces a minor error in the velocity calculation, basically ignoring half of the total force contribution, but IMHO this is not really a problem when we look at the different ways how we initialize a simulation: 

1. From a generator with or without velocities, we start from an unphysical state anyway to reach some equilibration; thus, it doesn't really make a difference. 
2. With brownian motion, the velocities are random anyways so 🤷 
3. When we initialize a simulation from a checkpoint an argument can be made that this actually has an effect, not sure however how impactful it is.

In the end, I'd prefer not to have an extra force calculation simply because I think the gain (more physical accuracy) vs the cost (more complex simulation loop) is not worth it. The idea of mdFlex is to be a test bench for AutoPas, thus having always one interaction calculation per loop makes statistics and everything easier.

How about we set `oldF = f` in the first iteration? That is still not 100% correct but a very close approximation that is cheap and keeps the simulation loop simple.

**Comment by thesamriel** [comment]
Last week, we collectively decided that we deliberately leave out the initial force computation for the reasons stated above by @FG-TUM.

**The following is in my opinion most likely to lead to confusion with the current implementation:**

In the first loop iteration, particle positions are updated only with respect to velocities.
This should be kept in mind when you want to monitor the exact movement of particles. Essentially, your molecules do not start the simulation at the given positions but are already moved by one timestep in the direction of their initial condition.

```C++
x₀, v₀ = initial_positions, initial_velocities

while (t < tₑₙd) {
    \\ Update positions
    x₁ = x₀ + Δt * (v₀ + F₀ * Δt * 0.5 / m)

    \\ First force update already with new positions!
    F₁ = computeForces(x₁)

    \\ Continue ...
```

This should most of the time not be an issue. I'm just stating this here to have it documented.
