### ISSUE TITLE
Exploding liquid simulation doesn't run on master

### ISSUE THREAD

**Issue by manishmishra6016** [AutoPas/AutoPas#863]
**Describe the bug**
As in the title. 

**To Reproduce**
1. Go to current `master` 
2. run `./md-flexible` for `explodingLiquid.yaml` case
3. See error after particles are initialized

**Screenshots**
![Screenshot from 2024-05-14 10-10-11](https://github.com/AutoPas/AutoPas/assets/24850773/df1d0c36-9f2e-46d3-bec3-0ee772243e14)

**Build environment (please complete the following information):**
* OS: Linux (PC)
* Compiler: gcc11.4

**Additional context**
@ManuelLerchner reported this issue on May 13, 2024
commit [`ed9d4ef0a`](https://github.com/AutoPas/AutoPas/tree/ed9d4ef0a82fa938c9101eb9a602e7162b73d696) seems to work fine!

**Comment by thesamriel** [comment]
![image](https://github.com/AutoPas/AutoPas/assets/43962524/1daf9ad7-741b-46cb-b4a0-145fb0aa337c)

This is what is happening in `exchangeHaloParticles` and what I was trying to say.  
Particle that is still owned is already outside the owned domain, but was not handled by the boundaries yet, because it will only be marked as a leaving particle in a rebuilding iteration.
