### ISSUE TITLE
Simplify c08 Base Step Setup

### ISSUE THREAD

**Issue by FG-TUM** [AutoPas/AutoPas#873]
**Is your feature request related to a problem? Please describe.**

The interaction pairs for the C08 base step are currently calculated in [`LCC08CellHandler::computeOffsets()`](https://github.com/AutoPas/AutoPas/blob/61e3e3859332d8c925d5eb9ff10fc03a3fdab2bb/src/autopas/containers/linkedCells/traversals/LCC08CellHandler.h#L135-L263).

This implementation is very hard to grasp.

**Describe the solution you'd like**
- [x] Simplify algorithm
- [ ] Investigate if the ordering has an impact of performance and optimize this.
- [x] Convert to free function (or `static` without using any state)

**Possible Implementation**
```cpp
std::vector<std::pair<int, int>> offsets;
offsets.reserve(14); // this is only for the case CSF >= 1
for (int z = -interactionCellsPerDim; z <= interactionCellsPerDim; ++z) {
  for (int y = -interactionCellsPerDim; y <= interactionCellsPerDim; ++y) {
    for (int x = -interactionCellsPerDim; x <= interactionCellsPerDim; ++x) {
      int baseCell = 0;
      int partnerCell = threeToOneD(x, y, z, cellsPerDim);
      if (x < 0) {
        baseCell -= x;
        partnerCell -= x;
      }
      if (y < 0) {
        baseCell -= y * cellsPerDim[0];
        partnerCell -= y * cellsPerDim[0];
      }
      if (z < 0) {
        baseCell -= z * cellsPerDim[0] * cellsPerDim[1];
        partnerCell -= z * cellsPerDim[0] * cellsPerDim[1];
      }
      const auto &[smallerIndex, biggerIndex] = std::minmax(baseCell, partnerCell);
      if (std::find(offsets.begin(), offsets.end(), std::make_pair(smallerIndex, biggerIndex)) == offsets.end()) {
        offsets.emplace_back(smallerIndex, biggerIndex);
      }
    }
  }
}
std::sort(offsets.begin(), offsets.end(), [](const auto &pair1, const auto &pair2) {
    const auto &[a1, b1] = pair1;
    const auto &[a2, b2] = pair2;

    if (a1 == a2) {
    return b1 < b2;
    } else {
    return a1 < a2;
  }
});
```

~**Describe alternatives you've considered**~

~**Additional context**~

**Comment by schuhmaj** [comment]
Some remarks I stumbled over - some might also be related to me not grasping everything. I just write everything down what comes to my mind:

- The naming `LCC08CellHandler`  suggests usage in `c08` based traversals, but it is also used in `sliced` traversal or `c04` traversal
- `VLCCellPairC08CellHandler` subclasses from `LCC08CellHandler`, this is a problem since:
  - The `processBaseCell` method is never ever used. Instead, we have a new method, `processCellListsC08` which gets the **same** arguments that are already present as `protected` members
  - It only requires the `offset` computation in the constructor
- `LCC08CellHandler::computeOffsets` is in its structure in major parts a clone of `LCC04SoACellHandler::computeOffsets`
- `LCC04Traversal::computeOffsets32Pack` - unnecessary exception check, should probably be an assert instead of an if

Modified Task List:

- [ ] Simplify `LCC08CellHandler::computeOffsets ` **and** `LCC04SoACellHandler::computeOffsets` - ideally merge them in a common free function
- [ ] Check if `LCC08CellHandler` and `LCC04SoACellHandler` can be superclassed
- [ ] Rename `LCC08CellHandler` and `LCC04SoACellHandler ` to something more general, e.g., `LCTraversalHelper` or something
- [ ] `LCC04Traversal::computeOffsets32Pack` Simplify the method to a constant or at least remove the `if` and use an `assert`

**Comment by FG-TUM** [comment]
A few pieces of context:

- The `c08` here refers to the base-step (aka. stencil) pattern. `sliced` Also uses this, and the `c04` base step is a combination of several `c08` steps.
- Good idea merging common behavior in all cell handlers!
- > It only requires the offset computation in the constructor

   Hence, why I think a free or static function for this would be nice.
- Renaming: I'd be slightly hesitant to rename this completely. "CellHandler" is by now an established term in AutoPas terminology. If the refactoring completely changes the structure here so that the old cell handler concept doesn't really exist anymore, it's, of course, a no-brainer. But then I'd go for something like `C08BaseStep` or similar.
- `assert`: Not a fan of this feature because it can lead to the code having different behavior in `Debug` vs `Release` mode. Yes, I know YOU wouldn't do that, but when less experienced people see it being used, there is a risk they do dangerous things with it. Therefore, we actually check in our CI that there is no `assert` in the code.
Here a better way would be to use `static_assert` to make sure the loops add up to 32 at compile time.
